### ISSUE TITLE
Question about defining custom object messages

### ISSUE THREAD

**Issue by mikaelarguedas** [intel/ros2_object_msgs#1]
Hi `ros2_object_msgs` maintainers!

I saw this package listed on the ROS 2 wiki and was curious.
Are you aware of the [vision_msgs](https://github.com/Kukanani/vision_msgs/tree/ros2/msg) project? This is a project started by OSRF and the ROS community to have "standard" messages for computer vision related interfaces. I'd be very interested in getting your feedback on these message definitions and if there are any blockers preventing these from being used in your projects.
Please feel free to comment here or on the [RFC on Discourse](https://discourse.ros.org/t/proposal-new-computer-vision-message-standards/1819) if you want to share your feedback with the community. Any feedback is welcome!

Thanks!

PS: there is a ROS 2 version of this package as well if you want to give it a shot

**Comment by Peter9606** [comment]
@mikaelarguedas Thanks for introducing this package. I didn’t know about that project before. One reason I split object_msgs as a stand-alone project is same as yours. I think it would be great if a universal definition of message could be used and personally I think your package is more serious than ours. It might take time to replace object_msgs with vision_msgs, as it has already been used in too many projects, but it's definitely planned in my mind.

**Comment by Kukanani** [comment]
Glad to hear that you'd like to move to `vision_msgs` in the future! Let me know if you would like any help with migration.

**Comment by dirk-thomas** [comment]
@xhuan28 @chaoli2 @yechun1 Is it planned to switch to `vision_msgs` before the upcoming release into ROS 2 Bouncy?

**Comment by chaoli2** [comment]
@dirk-thomas @mikaelarguedas @Kukanani 
Thanks very much for all your interests and suggestions. ```vision_msgs``` is quite helpful to our projects since it can unify the messages for computer vision interfaces. We'd like to consider how to replace original message projects with this one in future development. 

For ROS 2 Bouncy release, we are not going to use it after evaluation. Several existing projects (which are going to be released) depend on current ```object_msgs```, so we concern it risky to switch to  ```vision_msgs``` in such a short period to guarantee the functionality and reliability. For these existing projects, we'd like to put this effort in future release. Meanwhile, ```vision_msgs``` will be the prior message mechanism for future projects which are still under planing.

Once we work out detailed plan, we will update this thread and let you know. Comments and contributions are welcome. Thanks.

**Comment by Kukanani** [comment]
If there's anything I can do to make the package easier to use for your team, please let me know. I'm excited to get this package more widely adapted!

**Comment by chaoli2** [comment]
@Kukanani Thanks in advance for your support. Will do that during project development :)
